/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        ship: THREE.Mesh;
        back: THREE.Mesh;
        front: THREE.Mesh;
        weapons: THREE.Mesh;
        wings: THREE.Mesh;
    };
    materials: {
        base_blue: THREE.MeshStandardMaterial;
    };
};

export function VesselDefaultModel(props: JSX.IntrinsicElements["group"]) {
    const { nodes, materials } = useGLTF("/ship_default.glb") as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ship.geometry}
                material={nodes.ship.material}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.back.geometry}
                    material={materials.base_blue}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.front.geometry}
                    material={materials.base_blue}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.weapons.geometry}
                    material={materials.base_blue}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.wings.geometry}
                    material={materials.base_blue}
                />
            </mesh>
        </group>
    );
}

useGLTF.preload("/ship_default.glb");
