/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useEffect, useMemo, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";
import { SkeletonUtils, GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        manta_low: THREE.SkinnedMesh;
        Main: THREE.Bone;
    };
    materials: {
        ["Material.001"]: THREE.MeshStandardMaterial;
    };
};

export function VesselMantaGalleryModel(props: JSX.IntrinsicElements["group"]) {
    const group = useRef<THREE.Group>(null);
    const { scene, materials, animations } = useGLTF(
        "/ship_manta.glb"
    ) as GLTFResult;
    const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
    const { nodes } = useGraph(clone)
    const { actions } = useAnimations(animations, group);

    const manta_low = nodes.manta_low as THREE.SkinnedMesh;

    useEffect(() => {
        // eslint-disable-next-line
        (actions as any).Move?.play();
    }, [actions]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Manta_ship" rotation={[Math.PI / 2, 0, 0]}>
                    <skinnedMesh
                        castShadow
                        name="manta_low"
                        geometry={manta_low.geometry}
                        material={materials["Material.001"]}
                        skeleton={manta_low.skeleton}
                    />
                    <primitive object={nodes.Main} />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/ship_manta.glb");
